name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Java API Tests with FastAPI Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install FastAPI dependencies
        working-directory: bookstore
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI server in background
        working-directory: bookstore
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 --reload &
          sleep 5

      - name: Wait for FastAPI to be ready
        run: |
          until curl -s http://localhost:8000/health | grep "up"; do
            echo "Waiting for FastAPI..."
            sleep 2
          done

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Run Java API Tests
        run: mvn clean test

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure Report
        if: always()
        run: |
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz
          tar -xvzf allure.tgz
          ./allure-2.25.0/bin/allure generate allure-results --clean -o allure-report

      - name: Upload Allure HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git clone --branch=gh-pages https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} allure-gh-pages || git clone https://github.com/${{ github.repository }} allure-gh-pages
          cd allure-gh-pages
          
          # Remove old files
          git rm -rf ./*
          
          # Copy new report files
          cp -r ../allure-report/* .
          
          # Commit and push changes
          git add .
          git commit -m "Update Allure report from workflow run #${{ github.run_number }}" || echo "No changes to commit"
          git push origin gh-pages